In [ ]:
# Importing numpy library
import numpy as np

# Creating arrays
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Print the arrays
print("1D Array:\n", arr1)
print("2D Array:\n", arr2)
print("3D Array:\n", arr3)


1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Array shape
# Get the shape of the array
shape = arr2.shape
print("Shape of 2D array:", shape)

# Array reshaping
# Reshape a 1D array to a 2D array
reshaped_arr = arr1.reshape(1, 5)
print("Reshaped 1D to 2D array:\n", reshaped_arr)


Shape of 2D array: (2, 3)
Reshaped 1D to 2D array:
 [[1 2 3 4 5]]


In [ ]:
# Array slicing
# Slice elements from the first row and first two columns
slice_arr = arr2[0, 0:2]
print("Sliced array elements:\n", slice_arr)

# Array indexing
# Indexing the second element in the 1D array
index_value = arr1[1]
print("Second element in 1D array:", index_value)

# Boolean indexing
# Get elements greater than 3
bool_index = arr1[arr1 > 3]
print("Elements greater than 3 in 1D array:\n", bool_index)


Sliced array elements:
 [1 2]
Second element in 1D array: 2
Elements greater than 3 in 1D array:
 [4 5]


In [ ]:
# Array operations
# Element-wise addition
add_arr = arr1 + np.array([10, 10, 10, 10, 10])
print("Element-wise addition:\n", add_arr)

# Element-wise subtraction
sub_arr = arr1 - np.array([1, 1, 1, 1, 1])
print("Element-wise subtraction:\n", sub_arr)

# Element-wise multiplication
mul_arr = arr1 * np.array([2, 2, 2, 2, 2])
print("Element-wise multiplication:\n", mul_arr)

# Element-wise division
div_arr = arr1 / np.array([2, 2, 2, 2, 2])
print("Element-wise division:\n", div_arr)


Element-wise addition:
 [11 12 13 14 15]
Element-wise subtraction:
 [0 1 2 3 4]
Element-wise multiplication:
 [ 2  4  6  8 10]
Element-wise division:
 [0.5 1.  1.5 2.  2.5]


In [ ]:
# Matrix multiplication
mat_mul = np.dot(arr2, np.array([[1, 2], [3, 4], [5, 6]]))
print("Matrix multiplication result:\n", mat_mul)


Matrix multiplication result:
 [[22 28]
 [49 64]]


In [ ]:
# Aggregate functions
# Sum of elements in the array
sum_arr = np.sum(arr1)
print("Sum of elements in 1D array:", sum_arr)

# Mean of elements in the array
mean_arr = np.mean(arr1)
print("Mean of elements in 1D array:", mean_arr)

# Standard deviation of elements in the array
std_arr = np.std(arr1)
print("Standard deviation of elements in 1D array:", std_arr)


Sum of elements in 1D array: 15
Mean of elements in 1D array: 3.0
Standard deviation of elements in 1D array: 1.4142135623730951


In [ ]:
# Transpose of a matrix
# Transpose a 2D array
transpose_arr = arr2.T
print("Transpose of 2D array:\n", transpose_arr)


Transpose of 2D array:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Concatenate arrays
# Concatenate two 1D arrays
concat_arr = np.concatenate((arr1, np.array([6, 7, 8, 9, 10])))
print("Concatenated array:\n", concat_arr)

# Stack arrays
# Stack two 1D arrays vertically
stack_arr = np.vstack((arr1, np.array([6, 7, 8, 9, 10])))
print("Vertically stacked array:\n", stack_arr)


Concatenated array:
 [ 1  2  3  4  5  6  7  8  9 10]
Vertically stacked array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Split arrays
# Split a 1D array into three arrays
split_arr = np.array_split(arr1, 3)
print("Split arrays:\n", split_arr)


Split arrays:
 [array([1, 2]), array([3, 4]), array([5])]


In [ ]:
# Array creation functions
# Create an array of zeros
zeros_arr = np.zeros((3, 3))
print("Array of zeros:\n", zeros_arr)

# Create an array of ones
ones_arr = np.ones((3, 3))
print("Array of ones:\n", ones_arr)

# Create an identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)

# Create an array with random values
random_arr = np.random.random((3, 3))
print("Random array:\n", random_arr)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array:
 [[0.23670386 0.30554048 0.03001187]
 [0.63224172 0.25771693 0.43190112]
 [0.84306919 0.67098991 0.76410435]]


In [ ]:
# Array sorting
# Sort a 1D array
sorted_arr = np.sort(arr1)
print("Sorted 1D array:\n", sorted_arr)


Sorted 1D array:
 [1 2 3 4 5]


In [ ]:
# Mathematical functions
# Apply sin function to an array
sin_arr = np.sin(arr1)
print("Sin function applied to 1D array:\n", sin_arr)

# Apply exponential function to an array
exp_arr = np.exp(arr1)
print("Exponential function applied to 1D array:\n", exp_arr)

# Apply logarithm function to an array
log_arr = np.log(arr1)
print("Logarithm function applied to 1D array:\n", log_arr)


Sin function applied to 1D array:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exponential function applied to 1D array:
 [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm function applied to 1D array:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# Linear algebra functions
# Calculate the determinant of a matrix
determinant = np.linalg.det(np.array([[1, 2], [3, 4]]))
print("Determinant of matrix:\n", determinant)

# Calculate the inverse of a matrix
inverse_matrix = np.linalg.inv(np.array([[1, 2], [3, 4]]))
print("Inverse of matrix:\n", inverse_matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(np.array([[1, 2], [3, 4]]))
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Determinant of matrix:
 -2.0000000000000004
Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# Handling missing values
# Create an array with NaN values
nan_arr = np.array([1, 2, np.nan, 4, 5])
print("Array with NaN values:\n", nan_arr)

# Check for NaN values
nan_check = np.isnan(nan_arr)
print("NaN check:\n", nan_check)

# Replace NaN values with zero
replace_nan = np.nan_to_num(nan_arr)
print("Array after replacing NaN values:\n", replace_nan)


Array with NaN values:
 [ 1.  2. nan  4.  5.]
NaN check:
 [False False  True False False]
Array after replacing NaN values:
 [1. 2. 0. 4. 5.]


In [ ]:
# Array flattening
# Flatten a 2D array to a 1D array
flatten_arr = arr2.flatten()
print("Flattened 2D array to 1D:\n", flatten_arr)


Flattened 2D array to 1D:
 [1 2 3 4 5 6]


In [ ]:
# Array stacking
# Horizontal stacking of two arrays
hstack_arr = np.hstack((arr1, np.array([6, 7, 8, 9, 10])))
print("Horizontally stacked arrays:\n", hstack_arr)

# Depth stacking of two 3D arrays
dstack_arr = np.dstack((arr3, arr3))
print("Depth stacked 3D arrays:\n", dstack_arr)


Horizontally stacked arrays:
 [ 1  2  3  4  5  6  7  8  9 10]
Depth stacked 3D arrays:
 [[[ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]]

 [[ 7  8  9  7  8  9]
  [10 11 12 10 11 12]]]


In [ ]:
# Create an array with a sequence of numbers
sequence_arr = np.arange(1, 10, 2)
print("Array with sequence of numbers:\n", sequence_arr)

# Create an array with linearly spaced numbers
linspace_arr = np.linspace(0, 10, 5)
print("Array with linearly spaced numbers:\n", linspace_arr)

# Create an array with logarithmically spaced numbers
logspace_arr = np.logspace(0, 2, 5)
print("Array with logarithmically spaced numbers:\n", logspace_arr)


Array with sequence of numbers:
 [1 3 5 7 9]
Array with linearly spaced numbers:
 [ 0.   2.5  5.   7.5 10. ]
Array with logarithmically spaced numbers:
 [  1.           3.16227766  10.          31.6227766  100.        ]


In [ ]:
# Random numbers
# Create an array with random integers
randint_arr = np.random.randint(0, 10, (3, 3))
print("Array with random integers:\n", randint_arr)

# Create an array with random values from a normal distribution
randn_arr = np.random.randn(3, 3)
print("Array with random values from a normal distribution:\n", randn_arr)

# Set seed for reproducibility
np.random.seed(42)
seeded_rand_arr = np.random.rand(3, 3)
print("Seeded random array for reproducibility:\n", seeded_rand_arr)


Array with random integers:
 [[8 6 5]
 [9 0 8]
 [9 6 6]]
Array with random values from a normal distribution:
 [[-0.35265623 -1.01029987  0.18493181]
 [-0.06318649 -1.04187145 -1.43396953]
 [ 0.13404905 -1.61914005  0.07938242]]
Seeded random array for reproducibility:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [ ]:
# Universal functions
# Apply absolute value function
abs_arr = np.abs(np.array([-1, -2, -3, 4, 5]))
print("Absolute values:\n", abs_arr)

# Apply square root function
sqrt_arr = np.sqrt(arr1)
print("Square root of elements in array:\n", sqrt_arr)

# Apply power function
power_arr = np.power(arr1, 2)
print("Power function applied to array:\n", power_arr)


Absolute values:
 [1 2 3 4 5]
Square root of elements in array:
 [1.         1.41421356 1.73205081 2.         2.23606798]
Power function applied to array:
 [ 1  4  9 16 25]


In [ ]:
# Cumulative functions
# Cumulative sum
cumsum_arr = np.cumsum(arr1)
print("Cumulative sum of elements in array:\n", cumsum_arr)

# Cumulative product
cumprod_arr = np.cumprod(arr1)
print("Cumulative product of elements in array:\n", cumprod_arr)


Cumulative sum of elements in array:
 [ 1  3  6 10 15]
Cumulative product of elements in array:
 [  1   2   6  24 120]


In [ ]:
# Moving averages
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

mov_avg = moving_average(arr1, n=2)
print("Moving average of array:\n", mov_avg)


Moving average of array:
 [1.5 2.5 3.5 4.5]


In [ ]:
# Structured arrays
# Create a structured array
structured_arr = np.array([(1, 'John', 25), (2, 'Alice', 30)],
                          dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])
print("Structured array:\n", structured_arr)

# Accessing fields in structured array
ids = structured_arr['id']
names = structured_arr['name']
ages = structured_arr['age']
print("IDs from structured array:\n", ids)
print("Names from structured array:\n", names)
print("Ages from structured array:\n", ages)


Structured array:
 [(1, 'John', 25) (2, 'Alice', 30)]
IDs from structured array:
 [1 2]
Names from structured array:
 ['John' 'Alice']
Ages from structured array:
 [25 30]


In [ ]:
# Advanced indexing
# Integer array indexing
int_indexing = arr1[[0, 2, 4]]
print("Integer array indexing:\n", int_indexing)

# Boolean array indexing
bool_indexing = arr1[arr1 > 2]
print("Boolean array indexing:\n", bool_indexing)

# Fancy indexing
fancy_indexing = arr2[[0, 1], [1, 2]]
print("Fancy indexing result:\n", fancy_indexing)


Integer array indexing:
 [1 3 5]
Boolean array indexing:
 [3 4 5]
Fancy indexing result:
 [2 6]
