In [1]:
# Importing numpy library
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", arr1)

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Create a 3D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", arr3)


1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [2]:
# Get the shape of the array
shape = arr2.shape
print("Shape of 2D array:", shape)

# Reshape a 1D array to a 2D array
reshaped_arr = arr1.reshape(1, 5)
print("Reshaped 1D to 2D array:\n", reshaped_arr)


Shape of 2D array: (2, 3)
Reshaped 1D to 2D array:
 [[1 2 3 4 5]]


In [3]:
# Slice elements from the first row and first two columns
slice_arr = arr2[0, 0:2]
print("Sliced array elements:\n", slice_arr)

# Indexing the second element in the 1D array
index_value = arr1[1]
print("Second element in 1D array:", index_value)


Sliced array elements:
 [1 2]
Second element in 1D array: 2


In [4]:
# Get elements greater than 3
bool_index = arr1[arr1 > 3]
print("Elements greater than 3 in 1D array:\n", bool_index)


Elements greater than 3 in 1D array:
 [4 5]


In [5]:
# Add a scalar to an array
broadcast_arr = arr1 + 10
print("Broadcasting: Adding 10 to 1D array:\n", broadcast_arr)


Broadcasting: Adding 10 to 1D array:
 [11 12 13 14 15]


In [6]:
# Element-wise addition
add_arr = arr1 + np.array([10, 10, 10, 10, 10])
print("Element-wise addition:\n", add_arr)

# Element-wise subtraction
sub_arr = arr1 - np.array([1, 1, 1, 1, 1])
print("Element-wise subtraction:\n", sub_arr)

# Element-wise multiplication
mul_arr = arr1 * np.array([2, 2, 2, 2, 2])
print("Element-wise multiplication:\n", mul_arr)

# Element-wise division
div_arr = arr1 / np.array([2, 2, 2, 2, 2])
print("Element-wise division:\n", div_arr)


Element-wise addition:
 [11 12 13 14 15]
Element-wise subtraction:
 [0 1 2 3 4]
Element-wise multiplication:
 [ 2  4  6  8 10]
Element-wise division:
 [0.5 1.  1.5 2.  2.5]


In [7]:
# Matrix multiplication
mat_mul = np.dot(arr2, np.array([[1, 2], [3, 4], [5, 6]]))
print("Matrix multiplication result:\n", mat_mul)


Matrix multiplication result:
 [[22 28]
 [49 64]]


In [8]:
# Sum of elements in the array
sum_arr = np.sum(arr1)
print("Sum of elements in 1D array:", sum_arr)

# Mean of elements in the array
mean_arr = np.mean(arr1)
print("Mean of elements in 1D array:", mean_arr)

# Standard deviation of elements in the array
std_arr = np.std(arr1)
print("Standard deviation of elements in 1D array:", std_arr)


Sum of elements in 1D array: 15
Mean of elements in 1D array: 3.0
Standard deviation of elements in 1D array: 1.4142135623730951


In [9]:
# Transpose a 2D array
transpose_arr = arr2.T
print("Transpose of 2D array:\n", transpose_arr)


Transpose of 2D array:
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
# Concatenate two 1D arrays
concat_arr = np.concatenate((arr1, np.array([6, 7, 8, 9, 10])))
print("Concatenated array:\n", concat_arr)

# Stack two 1D arrays vertically
stack_arr = np.vstack((arr1, np.array([6, 7, 8, 9, 10])))
print("Vertically stacked array:\n", stack_arr)


Concatenated array:
 [ 1  2  3  4  5  6  7  8  9 10]
Vertically stacked array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
# Split a 1D array into three arrays
split_arr = np.array_split(arr1, 3)
print("Split arrays:\n", split_arr)


Split arrays:
 [array([1, 2]), array([3, 4]), array([5])]


In [12]:
# Create an array of zeros
zeros_arr = np.zeros((3, 3))
print("Array of zeros:\n", zeros_arr)

# Create an array of ones
ones_arr = np.ones((3, 3))
print("Array of ones:\n", ones_arr)

# Create an identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)

# Create an array with random values
random_arr = np.random.random((3, 3))
print("Random array:\n", random_arr)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array:
 [[0.88651251 0.3668614  0.62299801]
 [0.17135744 0.98940584 0.60492157]
 [0.88912033 0.42862484 0.53837952]]


In [13]:
# Sort a 1D array
sorted_arr = np.sort(arr1)
print("Sorted 1D array:\n", sorted_arr)


Sorted 1D array:
 [1 2 3 4 5]


In [14]:
# Apply sin function to an array
sin_arr = np.sin(arr1)
print("Sin function applied to 1D array:\n", sin_arr)

# Apply exponential function to an array
exp_arr = np.exp(arr1)
print("Exponential function applied to 1D array:\n", exp_arr)

# Apply logarithm function to an array
log_arr = np.log(arr1)
print("Logarithm function applied to 1D array:\n", log_arr)


Sin function applied to 1D array:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exponential function applied to 1D array:
 [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm function applied to 1D array:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [15]:
# Calculate the determinant of a matrix
determinant = np.linalg.det(np.array([[1, 2], [3, 4]]))
print("Determinant of matrix:\n", determinant)

# Calculate the inverse of a matrix
inverse_matrix = np.linalg.inv(np.array([[1, 2], [3, 4]]))
print("Inverse of matrix:\n", inverse_matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(np.array([[1, 2], [3, 4]]))
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Determinant of matrix:
 -2.0000000000000004
Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
